trel = ["лось", "корова", "руль"]
print(trel)
print(trel[0])
trel.append("конь")
print(trel)
trel.extend("sd")
print(trel)
trel.extend(["лор", 1])
print(trel)
trel.remove("s")
print(trel)
print(trel[0:5:2])
print("лось" in trel)
print("s" not in trel)